### ISSUE TITLE
Data seeding&ERROR:(No module named 'psycopg2' /No matching distribution found for psycopg2)

### ISSUE THREAD

**Issue by IT-HONGREAT** [IT-HONGREAT/django_food_project#10]
# Data, json으로 추출하고 관리하기

- posts의 데이터를 json파일로 추출해준다.
데이터를 관리하고 test하기에 좋다.

```python
#한 줄로 출력
python3 manage.py dumpdata posts > posts_data.json

#들여쓰기 적용
python3 manage.py dumpdata posts --indent=2 > posts_data.json
```

- 이렇게 하면 json 형태로 추출되는데, data를 수정하여 다시 load 시키면 서버에 올라간다.

```python
#불러오기
python3 manage.py loaddata posts_data.json
```

---

## 대용량의 데이터를 seeding

- 우선 django에서 제공하는 seed 기능을 설치해준다.

```python
pip install django seed
```

- settings파일의 installed_app 에서 django_seed 를 추가해준다.
그리고 터미널에서 명령어를 통해 원하는 만큼 데이터를 생성한다.

```python
python3 manage.py seed posts --number=50
```

### No matching distribution found for psycopg2
    
    
   - psycopg2 안됨 → psycopg2-binary 안됨
    
    
![image](https://user-images.githubusercontent.com/80932397/142594346-d98116f5-2682-45b2-ac25-b3b1c627af50.png)

    
   - 구글링으로 수많은 stackoverflow와 심지어 psycopg2 공식문서도 봤지만, 나에겐 유용하지 않음. 
   -나의 개발환경(mac OS Monterey <M1>, python - 3.9,  Django - 3.2.9, django-seed 0.3.1)
        
        [https://github.com/psycopg/psycopg2/issues/1286](https://github.com/psycopg/psycopg2/issues/1286)
        
    
    `brew install postgresql`
    
   이걸 설치하니 해결됨 → pip install psycopg2 (psycopg2 == 2.9.2 가 설치됨_최신버전임)
    
   - 정상적으로 data 생성
    
![image](https://user-images.githubusercontent.com/80932397/142594480-4bd647b6-aabb-4bb5-ae20-09395c9ddb28.png)

**Comment by Pancham97** [comment]
This is great. Thanks!

**Comment by IT-HONGREAT** [comment]
End issue.
